### ISSUE TITLE
Добавление видео из ресурса VK

### ISSUE THREAD

**Issue by vitkovI** [alxgrn/telefrag#1]
Когда добавляешь видео в редактор статей в певый раз, из вк видео по прямой ссылке в редактор статей, поначалу видео прогружается и проигрывается.
![Снимок экрана 2024-03-22 122002](https://github.com/alxgrn/telefrag/assets/33411151/a1ede462-ccc1-4482-9b21-2e324cf4f963)
Но после сохранения изменений и перехода  режим препромотра статьи, все видео заменяется на гифку ERROR. Видео из ютуба по доступу по ссылке - работают
Видео в вк находятся в открытом доступе, ограничений на просмотр нет

**Comment by alxgrn** [comment]
Исправил
