### ISSUE TITLE
Кнопка Отмены для окна Создания мероприятия

### ISSUE THREAD

**Issue by hardway777** [alxgrn/telefrag#23]
Кнопка Отмены для окна Создания мероприятия. Сейчас если щелкнуть мимо окна - оно закроется с потерей всех данных.

**Comment by alxgrn** [comment]
Так и задумано. Клик мимо окна равносилен нажатию ESC или клику по кнопке закрытия окна, что в свою очередь подразумевает отказ от создания мероприятия.
