### ISSUE TITLE
Проект не удаляется при удалении аватарки

### ISSUE THREAD

**Issue by vitkovI** [alxgrn/telefrag#26]
Проект не удаляется при удалении аватарки
![image](https://github.com/alxgrn/telefrag/assets/33411151/5ed2a1e2-fa79-489f-ac68-8000481bd1a5)
при удалении:
![image](https://github.com/alxgrn/telefrag/assets/33411151/6b0b4fd0-3a3f-4491-8040-d944ca754784)
на главной странице:
![image](https://github.com/alxgrn/telefrag/assets/33411151/560cbda2-00f9-47e5-9bdc-6047373df61e)

**Comment by alxgrn** [comment]
Что-то я наверное не очень понял описываемую проблему т.к. раньше нигде в интерфейсе не было возможности удаления проекта. Сейчас добавил такой пункт в меню проекта.

Но логотип и обложку все равно надо заранее удалять :)
