### ISSUE TITLE
(UX фича) Добавить возможность сворачивать ветки комментариев в обсуждениях под постом

### ISSUE THREAD

**Issue by vitkovI** [alxgrn/telefrag#27]
![image](https://github.com/alxgrn/telefrag/assets/33411151/7d639fb2-cba8-4b21-ad69-b6013e74a459)
Сейчас это нормально, но потом в больших тредах может стать проблемой

**Comment by alxgrn** [comment]
Читаешь мои мысли.
Как раз сейчас этим занимаюсь.

**Comment by alxgrn** [comment]
Пока так реализовал https://dailytelefrag.ru/article/128
Не очень доволен механизмом и понятно как его улучшать. Позже еще к нему вернусь.
