### ISSUE TITLE
Свободное место под курсором во время написания статей

### ISSUE THREAD

**Issue by vitkovI** [alxgrn/telefrag#3]
когда пишешь статью, хочется, чтобы внизу было бесконечное свободное пространство. Сейчас там всегда курсор упирается вниз страницы при достижении лимита, ощущение психологическое помехи снизу. Хочется чтобы курсор оставался всегда примерно на середине рабочего поля
Как например в редакторе статей в вк
![Снимок экрана 2024-03-22 135334](https://github.com/alxgrn/telefrag/assets/33411151/55484ce4-7b65-47bc-b214-3e1a75ebc23e)
сейчас курсор пирается в пол:
![Снимок экрана 2024-03-22 135429](https://github.com/alxgrn/telefrag/assets/33411151/7b01f7c4-f5eb-4951-85ff-f07e5665a699)

**Comment by alxgrn** [comment]
Добавил отступ внизу и поставил минимальный размер редактора чтобы когда он пустой был примерно размером со страницу
