### ISSUE TITLE
У проекта список статей и список публикаций блога совпадает

### ISSUE THREAD

**Issue by SaintHeiser** [alxgrn/telefrag#5]
И в блоге
![image](https://github.com/alxgrn/telefrag/assets/21117135/00346ecf-0336-4405-bc8e-96652513d32b)
И в статьях
![image](https://github.com/alxgrn/telefrag/assets/21117135/0a72596c-bdac-4fea-bf3e-7880c508c4db)
Одно и то же

**Comment by alxgrn** [comment]
fixed
